# Generated by Django 4.0.6 on 2023-03-31 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Train_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 31, 7, 8, 16, 547946, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
